export type EntityType =
  | 'applicationcontext'
  | 'calendarcache'
  | 'chat'
  | 'chatmessage'
  | 'competition'
  | 'event'
  | 'fixture'
  | 'fixtures'
  | 'leaguetable'
  | 'report'
  | 'season'
  | 'siteuser'
  | 'statistics'
  | 'team'
  | 'text'
  | 'user'
  | 'venue'
